src/client/ulogging/Discover.less, src/client/ulogging/DiscoverContent.js, src/client/ulogging/DiscoverUser.js, src/client/ulogging/Ulogging.js, src/common/routes.js
=> WIP: Ulogging page

src/client/components/ReputationTag.js, src/client/ulogging/Ulogging.js
Fixes #11
Added Ulogging page using ant collapsed and dropdown.
Does not contain the fix for the following editor:
https://user-images.githubusercontent.com/23729959/42942637-1eeb9764-8b93-11e8-8c65-61806c75623c.png
This will be addressed in a separate PR for issue #8
=> Updated ulogging page - convert to accordion; added editor link dropdown

src/client/components/Navigation/Topnav.js
=> Added tooltips to topnav menu

src/client/components/Sidebar/VideoEmbed.js, src/client/components/Sidebar/VideoEmbed.less, src/client/post/Write/Write.js
=> Added youtube embedded video

src/client/components/Sidebar/VideoEmbed.js, src/client/components/Sidebar/VideoEmbed.less, src/client/post/Write/Write.js
Reverts surpassinggoogle/UlogsV2#21
=> Revert "Revert "Added youtube embedded video""

src/client/components/Sidebar/LastDrafts.js, src/client/components/Sidebar/VideoEmbed.js, src/client/components/Sidebar/VideoEmbed.less, src/client/post/Write/Write.js, src/client/post/Write/editorActions.js
Fixes: Prior to this PR, the main-editor on ulogs.org couldn't autosave (draft) as it keeps redirecting to ulogs.org/editor. This has been fixed.
The main-editor now auto-saves accordingly!
=> Main Editor Bug Fix To Implement Auto-Save To The Main-Editor.

src/client/components/Editor/Editor.less, src/client/components/Editor/EditorUlogNed.js, src/client/components/Sidebar/LastDrafts.js, src/client/post/Write/Write.js, src/client/ulogging/Ulogging.js, src/common/routes.js
**Fixes** 
A new specialized editor was created called ulog-editor that can be accessed from https://ulogs.org/ulogging under the segment "Fanlove (Beliketerry)
=> The Creation Of The Ulog-Ned Editor On https://ulogs.org

EditorTeardrop.js, EditorUntalented.js, Write.js, routes.js, src/client/components/Editor/EditorTeardrop.js, src/client/components/Editor/EditorUntalented.js, src/client/post/Write/Write.js, src/common/routes.js
=> The #teardrops & #untalented Editors Created On Ulogs.org

src/client/ulogging/Ulogging.js
References #41 
* bug fix for collapse area stuck on activeKey (other items stuck being collapsed)
=> activate collapse segments using component's state

src/client/components/Editor/Editor.js, src/client/components/Editor/EditorBeLikeTerry.js, src/client/components/Editor/EditorMain.js, src/client/components/Editor/EditorSurpassingGoogle.js, src/client/components/Editor/EditorTeardrop.js, src/client/components/Editor/EditorUlogDIY.js, src/client/components/Editor/EditorUlogNed.js, src/client/components/Editor/EditorUlogSurpassingGoogle.js, src/client/components/Editor/EditorUntalented.js, src/client/components/Editor/UlogDropdown.js, src/client/components/Navigation/Topnav.js, src/client/components/Sidebar/LastDrafts.js, src/client/types/drafts.js
=> refactored ulog-dropdown - extracted as common component

src/client/components/Editor/Editor.js, src/client/components/Editor/EditorBeLikeTerry.js, src/client/components/Editor/EditorMain.js, src/client/components/Editor/EditorSurpassingGoogle.js, src/client/components/Editor/EditorTeardrop.js, src/client/components/Editor/EditorUlogDIY.js, src/client/components/Editor/EditorUlogNed.js, src/client/components/Editor/EditorUlogSurpassingGoogle.js, src/client/components/Editor/EditorUntalented.js, src/client/components/Editor/UlogDropdown.js, src/client/components/Navigation/Topnav.js, src/client/components/Sidebar/LastDrafts.js, src/client/types/drafts.js, src/client/ulogging/Ulogging.js
refactored ulog-dropdown - extracted as common component in relation to issue #53
=> refactored ulog-dropdown - extracted as common component in relation to issue #53

.env, src/client/components/Editor/EditorUlogHowto.js, src/client/components/Editor/EditorUlogQuotes.js, src/client/post/Write/Write.js, src/client/ulogging/Ulogging.js, src/common/routes.js
=> Added editor #ulog-quotes and #ulog-howto

src/client/components/Editor/EditorUlogDIY.js, src/client/components/Editor/EditorUlogHowto.js, src/client/components/Editor/EditorUlogQuotes.js, src/client/components/Editor/EditorUlogSurpassingGoogle.js
Some text edits applied to editor.js
=> Some Text Edits To Editor.js

src/client/components/Editor/EditorUlogQuotes.js, src/client/components/Editor/EditorUlogSurpassingGoogle.js
Issue #52 com completed!
> An "About #ulog-quotes" Text-Area (With Collapse Component) Added To The Top Of ulogs.org/created/ulog-quotes
=> An "About #ulog-quotes" Text-Area (With Collapse Component) Added To The Top Of ulogs.org/created/ulog-quotes

src/client/components/Editor/EditorUlogSurpassingGoogle.js, src/client/feed/Page.js
Text edits done to add <a href= function to some of the text containing URLS to make these links clickable and able to redirect. This was done to some text on ulogs.org/ulog-surpassinggoogle and some text on https://ulogs.org/created/ulog-quotes
=> Simple Text Edits

src/client/components/Editor/EditorUlogSurpassingGoogle.js
Applied ulog-quotes collapse for other filters - trending, new, active and hot
=> Applied ulog-quotes collapse for other filters.

src/client/feed/Page.js, src/common/routes.js
>BugFix For Replies (#ulog-quotes) Which Redirects To The #ulog-quotes Editor.
=> BugFix For Replies (#ulog-quotes) Which Redirects To The #ulog-quotes Editor.

src/client/feed/Feed.less, src/client/feed/Page.js
Simple text with collapse component was added as header to #ulog-diy on https://ulogs.org
=> Text added as Header to https://ulogs.org/created/ulog-diy

src/client/feed/Page.js
=> Some Error During Merge (Remedy)

src/client/feed/Feed.less, src/client/feed/Page.js
Reverts surpassinggoogle/UlogsV2#71
=> Revert "Some Error During Merge (Remedy)"

src/client/feed/Feed.less, src/client/feed/Page.js
=> Inserting header text to the top of Ulog-Diy category

src/client/feed/Feed.less, src/client/feed/Page.js
Reverts surpassinggoogle/UlogsV2#75
=> Revert "Inserting header text to the top of Ulog-Diy category"

src/client/feed/Feed.less, src/client/feed/Page.js
=> re-commiting ulog-diy header text

src/client/feed/Feed.less, src/client/feed/Page.js
Reverts surpassinggoogle/UlogsV2#77
=> Revert "re-commiting ulog-diy header text"

src/client/feed/Page.js, src/client/feed/UlogCaption.js
=> Added ulog-diy caption 

src/client/components/Editor/EditorUlogSurpassingGoogle.js, src/client/feed/Page.js
1. Unnecessary codes removed
2. Headers Text (With Collapse Component) Added To #ulog-diy & #ulog-howto On ulogs.org
=> Bug Fixes & Headers Text (With Collapse Component) Added To #ulog-diy & #ulog-howto On ulogs.org

src/client/feed/Page.js, src/client/feed/UlogCaption.js
Added header-text and collapse component to category ulog-surpassinggoogle.
=> Added header-text and collapse component to category ulog-surpassinggoogle on ulogs.org

src/client/feed/Page.js, src/client/feed/UlogCaption.js
Added Header-Text To #teardrops On Ulogs.org
=> Added Header-Text To Category "Teardrops" On Ulogs.org

src/client/feed/UlogCaption.js
Re-added header-text and collapse component to category ulog-diy on ulogs.org
=> Re-added header-text and collapse component to category ulog-diy

src/client/feed/Page.js, src/client/feed/UlogCaption.js
Added header-text and collapse component to category #untalented on ulogs.org
=> Added header-text and collapse component to category untalented

src/client/feed/Page.js, src/client/feed/UlogCaption.js
> Added Header-Text To Category #ulog-ned On Ulogs.org
=> Added Header-Text To Category ulog-ned On Ulogs.org

src/client/feed/Page.js, src/client/feed/UlogCaption.js
Added header text to the #ulography category on ulogs.org
=> Added header text to the ulography category on ulogs.org

src/client/components/Editor/Editor.js
> Added additional collapse component with defined text to ulogs.org/editor.
=> Added additional collapse component with defined text to ulogs.org/editor

src/client/components/Editor/Editor.js
Fixes 
> Some text formatting to ulogs.org/editor style-guide.
=> Some text formatting to ulogs.org/editor style-guide.

src/client/components/UserMenu.js, src/client/feed/feedReducer.js, src/client/helpers/apiHelpers.js, src/client/helpers/stateHelpers.js, src/client/user/UserUlogs.js, src/common/routes.js
- copied `UserProfile.js`
- added a `ulogs` route
- added the tab in `UserMenu.js`
=> added "My Ulogs" tab

src/client/feed/Page.js, src/client/feed/UlogCaption.js
> Added header text to category ulog-blocktrades on ulogs.org
=> Added header text to category ulog-blocktrades on ulogs.org etc

src/client/feed/Page.js, src/client/feed/UlogCaption.js
Added header text (with collapse component) to category ulog-showerthoughts on ulogs.org
=> Added header text to category ulog-showerthoughts on ulogs.org etc

src/client/components/MainMenu.js, src/client/components/MainMenu.less, src/client/feed/Feed.less, src/client/feed/Page.js
According to: https://steemit.com/@surpassinggoogle/task-request-kindly-create-a-new-tab-s-area-across-ulogs-org
* Added main menu bar
* Fixed carousel style issue
External links (youtube) open in new window. Internal links are handled by javascript so that the app does not get reloaded unnecessarily.
There was a unintended spacing between the header carousel and the new menu. I fixed that.
=> Added Main Menu Bar

src/client/feed/Page.js, src/client/feed/UlogCaption.js
This task contains mostly text edits to the Ulogcaption.js as well as an addition of header text to category ulogifs and ulog-utopian
=> Added some more header text to fresh ulog-subtag categories etc

src/client/feed/Page.js, src/client/feed/UlogCaption.js
The Discover list on ulogs.org now updates according to the list of steem accounts followed by https://ulogs.org/@uloggers
=> "Discover" List On ulogs.org Now Made "Dynamic".

src/client/components/Editor/Editor.js, src/client/feed/Page.js, src/client/feed/UlogCaption.js
Added Header Text To Category ulog-surfyogi On ulogs.org as well as some other text edits
=> Added Header Text To Category ulog-surfyogi On ulogs.org etc

src/client/user/userActions.js
=> display certified ulogger even if user not logged in

src/client/components/Editor/Editor.js, src/client/feed/Page.js, src/client/feed/UlogCaption.js
* display certified ulogger in post content
* changed wording from 'verified' to 'certified' ulogger
=> Added Feature To Display "Certifed Ulogger" Badge With Post Content

src/client/comments/Comments.js, src/client/components/Comments/Comment.js, src/client/components/Comments/Comments.js
=> added certified ulogger icon to comments

src/client/comments/commentsActions.js
Will now display front-end (app) used when submitting comment.
=> updated app info when submitting comment

src/client/comments/commentsActions.js, src/client/components/Utils/Redirect.js, src/client/settings/Settings.js
Prior to now, users could no longer use ulogs.org when they mistakenly select the "Ulogs beta" option that was existent in the settings of user-profiles. 
This Ulog Beta feature has been removed completely from the settings of user-profiles as seen below:
=> The "Ulog Beta" Feature Has Been Removed From Ulogs.org

src/client/feed/Page.js, src/client/feed/UlogCaption.js
Added header text (style-guide) with collapse component to the categories ulog-teamsteem, ulog-kusknee and ulog-papapepper on ulogs.org
=> Added Header Text(style-guide) To Several Categories On Ulogs.org

src/client/feed/Page.js, src/client/feed/UlogCaption.js
- Update steemscript based on latest codes not on stable release
- Updated yarn.lock
- Merge pull request #130 from surpassinggoogle/hotfix-package-json
- Hotfix package json
=> HotFix: Version "Ulogs" Now Re-Shows For Posts & Comments Created Using ulogs.org

src/client/components/StoryFooter/Buttons.js, src/client/helpers/constants.js
=> Delegate Custom SP

src/client/components/StoryFooter/ContactButton.js, src/client/components/VerifiedUloggers/VerifiedUloggers.js, src/client/feed/UlogCaption.js
Fixes #
Created a verifiedulogger component which improves the styling of existing functionality and makes it more modular
=> Verified u logger

src/client/components/VerifiedUloggers/VerifiedUloggers.css, src/client/components/VerifiedUloggers/VerifiedUloggers.js, src/client/feed/UlogCaption.js
Fixes #
Improved the ease of use to add new verified u loggers and included the avatar component
Before
After
=> improvements to verified u loggers

src/client/components/Sidebar/WalletSidebar.js, src/client/components/VerifiedUloggers/VerifiedUloggers.js
=> Verified u logger improvements

src/client/components/Button/Vote.js, src/client/widgets/VoteButton.js, src/client/witnesses/DiscoverWitness.js, src/client/witnesses/DiscoverWitnesses.js, src/client/witnesses/Witnesses.js, src/client/witnesses/Witnesses.less, src/common/routes.js, yarn.lock
Created a dynamic "ulog-witnesses" page allowing users to easily follow and vote on steem witnesses who are also certified uloggers. The growing list of certified uloggers is on https://ulogs.org/discover
=> Created A Vote On ulog-witnesses page On Ulogs.org/vote-ulog-witnesses

src/client/Wrapper.js, src/client/components/Editor/Editor.js, src/client/components/Editor/EditorMain.js, src/client/components/Editor/EditorSurpassingGoogle.js, src/client/components/Editor/EditorUlogDIY.js, src/client/components/Editor/EditorUlogHowto.js, src/client/components/Editor/EditorUlogNed.js, src/client/components/Editor/EditorUlogQuotes.js, src/client/components/Editor/EditorUlogSurpassingGoogle.js, src/client/components/Navigation/Topnav.js, src/client/components/Navigation/Topnav.less, src/client/components/Story/StoryFull.js, src/client/components/StoryFooter/DelegateButton.js, src/client/components/StoryFooter/DelegateButton.less, src/client/ulogging/Ulogging.js
Fixes #
Cleaned up an error in /editor where a div was inside a p
* Added editors page, with the pen icon linking to it now, with all panels initially collapsed.
* Made default tag '#ulog' required in all ulog-editors (you can still delete it, because the React component requires it, but it will not allow posts without it)
* Added delegate button to certified uloggers in all post formats (story, story-full). z-index tinkering was required, pretty easy to change if it needs to go up or down.
Run and look at changes on /ulogging, the ulog editors, and when expanding certified uloggers posts. All changes are tested to not break functionality in dev mode.
=> Completed Tasks 1, 2, 7, and 9

package.json, src/client/Wrapper.js, src/client/components/Editor/EditorMain.js, src/client/components/Editor/EditorSurpassingGoogle.js, src/client/components/Editor/EditorUlogDIY.js, src/client/components/Editor/EditorUlogHowto.js, src/client/components/Editor/EditorUlogNed.js, src/client/components/Editor/EditorUlogQuotes.js, src/client/components/Editor/EditorUlogSurpassingGoogle.js, src/client/components/Navigation/Topnav.js, src/client/feed/Feed.less, src/client/feed/Page.js, src/client/helpers/apiHelpers.js, src/client/tags/UlogTags.js, src/client/tags/UlogTags.less, src/common/routes.js, yarn.lock
Fixes #
Cleaned up some spots where I used loose rather than strict equalities in last PR.
* Added embedded videos to the banner
* Added ulog-subtags page and button in user dropdown menu
Run it up and check /ulog-subtags and the banner wherever it normally is found (requires authentication).
=> Added ulog-subtags page and embedded videos in banner (Tasks 6 and 4)

src/client/tags/UlogTags.js
Fixes #
Removed testing purpose console logs from UlogTags
* Deleted console.log statements
=> removed console logs

src/client/app/Sidebar/RightSidebar.js, src/client/components/Button/View.js, src/client/components/Navigation/Sidenav.js, src/client/components/Sidebar/Story.js, src/client/components/Sidebar/Topics.js, src/client/components/Sidebar/UlogStories.js, src/client/widgets/ViewButton.js
- ulog stories column added To Ulogs.org (Upon Login) 
- & new sidebars.
=> ulog stories column added To Ulogs.org (Upon Login) & new sidebars.

src/client/app/Sidebar/ChatBar.js, src/client/app/Sidebar/RightSidebar.js, src/client/components/ModalEditor/ModalEditor.js, src/client/components/ModalEditor/ModalEditor.less, src/client/components/ModalEditor/ModalEditorFooter.js, src/client/components/ModalEditor/UlogStoryTags.js, src/client/components/Navigation/Sidenav.js, src/client/components/Sidebar/InterestingUloggersWithAPI.js, src/client/components/Sidebar/UlogStories.js, src/client/feed/Page.js
Fixes #
Fixed errors being thrown due to setstate called before mount, jsx element errors, marketplace button being active all the time.
Added the editor to ulogstories, have not styled yet. Have not added ability to open stories to ulogstories yet, due to the code being obtuse and hard to integrate this ability into. Might have to rewrite most of the logic behind the panel.
Start up server, login, check to make sure ulog stories and other sidebar item look okay, then click the plus in ulogstories. Check functionality of tag picker, input, and image areas. Check post to make sure posting from modal editor works as intended.
=> Added modal editor to ulog stories

src/client/components/Sidebar/UlogStories.js, src/client/feed/Page.js
Fixes #
Commented out the chatbar for loading speed, since it isn't currently working.
=> commented out chatbar for now

src/client/components/Navigation/Sidenav.js
Reverts surpassinggoogle/UlogsV2#164
=> Revert "fixed login error"

src/client/components/Sidebar/UlogStories.js, src/client/feed/Page.js
Reverts surpassinggoogle/UlogsV2#166
=> Revert "commented out chatbar for now"

src/client/components/Navigation/Sidenav.js
Some api changes was done and algorithm changes to restore ulogs.org/ulog-subtags to functionality
=> HotFix: To Restore ulogs.org/ulog-subtags To Functionality

src/client/app/Sidebar/RightSidebar.js, src/client/components/Sidebar/ChatBar.js, src/client/components/Sidebar/ChatUser.js, src/client/components/Sidebar/SidebarContentBlock.less, src/client/components/Sidebar/UlogGamesExchanges.js, src/client/components/Sidebar/UlogGamesExchangesUser.js, src/client/components/Sidebar/User.less
Implement ChatBar Component #181
=> Implement ChatBar Component #181

package.json, src/client/app/Sidebar/RightSidebar.js, src/client/components/QuickPostEditor/QuickPostEditor.js, src/client/components/Sidebar/ChatBar.js, src/client/components/Sidebar/FeedSidebar.js, src/client/components/Sidebar/SidebarContentBlock.less, src/client/components/Sidebar/UlogGamesExchanges.js, src/client/components/Sidebar/UlogStories.js, src/client/components/Sidebar/UloggerTVThumbnailView.js, src/client/components/Sidebar/VideoExample.js, src/client/components/UlogsBanner.js, src/client/feed/Page.js, src/client/feed/UlogCaption.js, src/client/steemConnectAPI.js, yarn.lock
=> Fixed #183 and #184

src/client/app/Sidebar/RightSidebar.js, src/client/components/Sidebar/ChatBar.js, src/client/components/Sidebar/ChatUser.js, src/client/components/Sidebar/InterestingPeople.js, src/client/components/Sidebar/InterestingUloggersWithAPI.js, src/client/components/Sidebar/UlogGamesExchanges.js, src/client/components/Sidebar/UlogGamesExchangesUser.js, src/client/components/Sidebar/UloggerTVThumbnailView.js, src/client/components/Sidebar/User.js, src/client/feed/Page.js, src/client/feed/UlogCaption.js, src/client/feed/feedReducer.js
=> Fix ui changes and pre login and post login state of chat bar component

src/client/steemConnectAPI.js
=> Fix env variable issue

.env, package.json, src/client/app/Sidebar/RightSidebar.js, src/client/components/QuickPostEditor/QuickPostEditor.js, src/client/components/Sidebar/ChatBar.js, src/client/components/Sidebar/ChatUser.js, src/client/components/Sidebar/FeedSidebar.js, src/client/components/Sidebar/InterestingPeople.js, src/client/components/Sidebar/InterestingUloggersWithAPI.js, src/client/components/Sidebar/SidebarContentBlock.less, src/client/components/Sidebar/UlogGamesExchanges.js, src/client/components/Sidebar/UlogGamesExchangesUser.js, src/client/components/Sidebar/UlogStories.js, src/client/components/Sidebar/UloggerTVThumbnailView.js, src/client/components/Sidebar/User.js, src/client/components/Sidebar/VideoExample.js, src/client/components/UlogsBanner.js, src/client/feed/Page.js, src/client/feed/UlogCaption.js, src/client/feed/feedReducer.js, yarn.lock
Reverts surpassinggoogle/UlogsV2#204
=> Revert "Revert "Partial Fix For #183 And #184""

src/client/app/Sidebar/RightSidebar.js, src/client/components/Sidebar/FeedSidebar.js, src/client/components/Sidebar/InterestingUloggersWithAPI.js, src/client/components/Sidebar/OverseeingUloggers.js, src/client/components/Sidebar/UlogGamesExchanges.js, src/client/components/Sidebar/UlogOverseer.js, src/client/components/Sidebar/User.js, src/client/components/Story/Story.js, src/client/components/UlogsBanner.js, src/client/feed/Page.js, src/client/feed/SubFeed.js, src/client/locales/default.json, src/server/renderers/ssrRenderer.js
- The Ulog-games/exchange column was enhanced. 
- Overseeing uloggers column was added
- Header banner improved.
- Interesting uloggers column was returned to homepage
=> Fixes To Former Issue #183

src/client/feed/UlogCaption.js
=> typo error for ulog-surpassinggoogle

src/client/components/CommentFooter/Buttons.js, src/client/components/CommentFooter/CommentFooter.js, src/client/components/CommentFooter/DelegateButton.js, src/client/components/CommentFooter/DelegateButton.less, src/client/components/Comments/Comment.js, src/client/components/Story/StoryFull.js
=> Add U-Promote to Post + Add U-Promote and Delegate to Comment

src/client/components/AnnouncementBanner.js, src/client/components/Story/StoryFull.js
=> auto-shrink u-promote; change banner close icon color to white

src/client/components/Sidebar/UlogStories.js, src/client/components/UlogStoryEditor/UlogStoryEditor.js, src/client/components/UlogStoryEditor/UlogStoryEditorFooter.js
=> Add bottom info text to ulog story quick editor

src/client/components/Sidebar/UlogStories.js, src/client/components/Sidebar/UlogStory.js, src/client/components/UlogStoryEditor/UlogStoryEditor.js, src/client/components/UlogStoryEditor/UlogStoryEditorFooter.js
* display ulog stories from newest to oldest
* add view more
* display post when View button is clicked
=> Display Ulog Stories from newest to oldest + View More

src/client/bropro/Bropro.js, src/client/bropro/bropro.css
added the missing css that was forgotten in https://github.com/surpassinggoogle/UlogsV2/commit/1ec4623272056e90c1bfea5cb406de075456363c
=> add broprocss

src/client/bropro/Brocard.js, src/client/bropro/Bropro.js, src/client/bropro/Notification.js, src/client/bropro/bropro.css
added wanted notification for click on button as described here: https://github.com/surpassinggoogle/UlogsV2/issues/240
=> added notification component

src/client/bropro/ExtraClout.js, src/client/bropro/FavoriteMentor.js, src/client/bropro/PopularCommunity.js, src/client/contact/Contact.js, src/client/grow/Grow.js, src/common/routes.js
added ExtraClout.js
linked it in grow page
added route
direct available under /extra-clout
added FavoriteMentor.js
linked it in grow page
added route
direct available under /favorite-mentor
added PopularCommunity.js
linked it in grow page
added route
available under /popular-community
changed route for contact page to send-us-a-gift
changed link in grow page
=> added landingpages - changed routes

src/client/components/Sidebar/UlogGamesExchanges.js, src/client/components/Sidebar/UlogGamesExchangesUser.js
=> add logic to split ulog-games and ulog-exchanges stories

yarn.lock
=> Added yarn.lock

src/client/wallet/Transfer.js
Fixes #
Fixed insufficient balance when attempting to transfer TEARDROPS
Pulled in the users current teardrops balance for validation against requested send amount
login
Select Transfer
Enter recipient
Select "TEARDROPS"
Enter required transfer balance
Select "Continue"
=> Update Teardrops balance validation

src/client/feed/Page.js
=> add ulog subtag generic (or empty sub-tag) banner and collapse

src/client/feed/Page.js, src/client/wallet/Transfer.js
Added A Generic Template For Prospective 'Ulog-Subtags'
=> Added A Generic Template For Prospective 'Ulog-Subtags'

src/client/wallet/Transfer.js, src/client/wallet/WalletTransaction.js
=> Add Steem Keychain Support

src/client/community/CreateCommunity.js, src/client/helpers/community.js
=> Create Ulog Communities Modifications
